### ISSUE TITLE
web interface not displaying

### ISSUE THREAD

**Issue by danglingptr0x0** [eagledot/hachi#3]
The web interface is only displaying the footer under a win10 VM. I've set everything up according to your README.md. Caddy is working properly since it displays the footer, which is in the static dir, which is defined in the Caddyfile. I tried using port 5000 first, and then also 2019 and 8200, but none of them brought up the interface. I even tried using several browsers, to no avail.

Any ideas?
Thanks

**Comment by kuldeepx** [comment]
I was unable to replicate same on Windows10 VM. 

In your case, it seems `caddy` is serving `index.html` but browser has some issues loading `js module`.

We need more information to check this issue. Can you please share browser network  logs?
(in `hachi` index page in your browser `right-click -> inspect -> Network -> Reload Page`) 

Also share your `./static/` folder structure. In case you might be missing some file.

**Comment by danglingptr0x0** [comment]
Weirdly enough, there are now no issues after having redeployed it. There was likely some corruption or a missing file.

**Comment by just-a-pancil** [comment]
Hello, same problem. Tried on debian 12 and on win 10 VM. Can help?
![3](https://github.com/eagledot/hachi/assets/42276706/d83b6a00-1a10-44b2-a3c0-6ca9afe27092)
![2](https://github.com/eagledot/hachi/assets/42276706/7874d8b5-052f-44b0-b7f6-7af301c46389)
![1](https://github.com/eagledot/hachi/assets/42276706/7acfe5ee-4d16-4397-a4e9-901ca5621845)
