### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by just-a-pancil** [eagledot/hachi#5]
Hello! I really love your project! I have been looking for such functionality for a long time. 
 I have 404 Not Found problem. Tried on debian 12 and on win 10 VM. Can you help, please?
![3](https://github.com/eagledot/hachi/assets/42276706/d83b6a00-1a10-44b2-a3c0-6ca9afe27092)
![2](https://github.com/eagledot/hachi/assets/42276706/7874d8b5-052f-44b0-b7f6-7af301c46389)
![1](https://github.com/eagledot/hachi/assets/42276706/7acfe5ee-4d16-4397-a4e9-901ca5621845)

**Comment by eagledot** [comment]
Application/flask server is running behind a  Caddy Server  which is at address http://localhost:5000 as defined in this [caddy file](https://github.com/eagledot/hachi/blob/main/Caddyfile). 

So try using http://localhost:5000 as base url .

**Comment by just-a-pancil** [comment]
> Application/flask server is running behind a Caddy Server which is at address http://localhost:5000 as defined in this [caddy file](https://github.com/eagledot/hachi/blob/main/Caddyfile).
> 
> So try using http://localhost:5000 as base url .

Then Firefox can’t establish a connection to the server at 127.0.0.1:5000.

**Comment by eagledot** [comment]
Is caddy running ?
Both Caddy (localhost:5000) and flask server (localhost:8200) must be running at all times.

Refer to the [Usage section of readme](https://github.com/eagledot/hachi?tab=readme-ov-file#usage) .

**Comment by just-a-pancil** [comment]
I've added 
```
{
	admin 127.0.0.1:2020
}

```
to hachi/Caddyfile because of error:
`Error: performing request: Post "http://localhost:2019/stop": dial tcp [::1]:2019: connect: connection refused`

then uninstalled Caddy with 
`sudo rm /etc/apt/sources.list.d/caddy-stable.list`
`sudo apt remove caddy`

Then installed Caddy again. I didn't even interrupted semantic_search.py while reinstalling caddy. 
It worked. Thank you for your answers, it just needed to be reinstalled.
